---
- set_fact:
    play_list:
      - configmaps
      - deployments
      - services
      - servicemonitors

- set_fact:
    play_list: "{{ play_list | reverse | list }}"
  when: state == "absent"

- include_tasks: "{{ play }}.yml"
  loop: "{{ play_list }}"
  loop_control:
    loop_var: play
