- name: ConfigMap for {{ consumer_type }} consumer
  oc_obj:
    state: "{{ state }}"
    name: "{{ consumer_type }}-config-{{ item.name }}"
    namespace: "{{ sa_telemetry_consumers_namespace }}"
    kind: ConfigMap
    content:
      path: /tmp/cmout
      data: "{{ lookup('template', '{{ consumer_type }}-consumer-configmap.yaml.j2') | from_yaml }}"
  ignore_errors: true
  with_items: "{{ sa_telemetry_node_labels }}"
