- name: DeploymentConfig for {{ consumer_type }} consumer
  oc_obj:
    state: "{{ state }}"
    force: yes
    name: "{{ consumer_type }}-consumer-{{ item.name }}"
    namespace: "{{ sa_telemetry_consumers_namespace }}"
    kind: dc
    content:
      path: /tmp/dout
      data: "{{ lookup('template', '{{ consumer_type }}-consumer-deployment.yaml.j2') | from_yaml }}"
  ignore_errors: true
  with_items: "{{ sa_telemetry_node_labels }}"
