- name: ServiceMonitor for {{ consumer_type }} consumer
  oc_obj:
    state: "{{ state }}"
    name: "{{ consumer_type }}-consumer-{{ item.name }}"
    namespace: "{{ sa_telemetry_consumers_namespace }}"
    kind: ServiceMonitor
    content:
      path: /tmp/smout
      data: "{{ lookup('template', '{{ consumer_type }}-consumer-service-monitor.yaml.j2') | from_yaml }}"
  ignore_errors: true
  with_items: "{{ sa_telemetry_node_labels }}"
  when: consumer_type == "metrics"
