- name: Service for {{ consumer_type }} consumer
  oc_service:
    state: "{{ state }}"
    name: "{{ consumer_type }}-consumer-{{ item.name }}"
    namespace: "{{ sa_telemetry_consumers_namespace }}"
    labels:
      sa-telemetry-app: "{{ consumer_type }}-consumer-{{ item.name }}"
      app: "{{ consumer_type }}-consumer"
      node: "{{ item.name }}"
    ports:
    - name: "{{ consumer_type }}"
      port: 8081
      targetPort: 8081
      protocol: TCP
    selector:
      sa-telemetry-app: "{{ consumer_type }}-consumer-{{ item.name }}"
  with_items: "{{ sa_telemetry_node_labels }}"
